title:        <a href="http://radiatta.github.io">Eduardo Prado</a> 
tagline:      'IOS Development'
description:  'B.S in Biomedical Engineer, <a href="http://RADIATTA.GITHUB.IO" target="_blank">iOS</a> Developer.Hacker.'
url:          http://hsi-medicalsolutions.github.io
version:      1.1.1
author:
  name:       ''
  email:      ''
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
